### PR TITLE
Remove postgres uid (70) and gid (70)

### PR DESCRIPTION
**Pull request by biofer76**
Updated Dockerfile to remove postgres user and group, it allows to attach container to an exiting PostreSQL container.

### CODE REVIEW

**Comment by macropin** [comment]
This is a potentially breaking change, so we'll have note that when releasing.

Also if we're going to remove this user/group we should remove all others that are unnecessary and potentially conflicting with the defaults from other distros.

**Comment by macropin** [comment]
You didn't need to close it. I'm happy to accept a PR. I'd just like to see some the other unnecessary user/groups removed as well.

**Comment by biofer76** [comment]
Ok, that's fine.

**Comment by macropin** [comment]
Ref: https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/usernames.html

**Comment by macropin** [comment]
Postgres has been removed from Alpine 3.11 base #51.

Closing for now. We can reopen if you wish to have a crack at removing the unused accounts.

**Pull request closed without merging**
