### PR TITLE
Add custom login shell

### PR DESCRIPTION
**Pull request by FlyingOnion**
Customize login shell by specifying the 4th param. This is helpful for git servers.
Adding an if statement to make it compatible with previous versions.

### CODE REVIEW

**Comment by FlyingOnion** [comment]
For git users, use `git:<uid>:<gid>:/sbin/nologin`.
If shell is not specified, the default `/bin/sh` is used.

**Comment by macropin** [comment]
@FlyingOnion did you mean to close this? It looks useful.

**Comment by FlyingOnion** [comment]
> @FlyingOnion did you mean to close this? It looks useful.

Some details still need to be confirmed, and it is probably not suitable for git server. They have their own formats of public keys. I will open a new one.

**Comment by macropin** [comment]
FWIW support for changing the shell was added in #55

**Pull request closed without merging**
