### PR TITLE
Multiarch support for arm32v7 and arm32v8

### PR DESCRIPTION
**Pull request by guysoft**
This PR adds dockerfiles that are used in this repo: https://hub.docker.com/repository/docker/guysoft/sshd

Also hooks that build a multiarch manfest for latest.

They are used to provide this service for all raspsberrypi versions and also intel.

### CODE REVIEW

**Comment by JenswBE** [comment]
Seems we are both interested in multi-arch support: https://github.com/panubo/docker-sshd/issues/59

FYI, setup could be simplified by using Docker BuildX (native or with GitHub Actions). This will handle the complexity of using QEMU and allows to build for multiple architectures using a single `Dockerfile`.

**Comment by guysoft** [comment]
Indeed, though it depends on which platform you want to build and push AFAIK (didn't check since I posted this) there is no buildx on docker hub.

Both dockerhub and github actions are proprietary ci so I don't really think its work moving from one to the other. In a way the only one that is open is GitLab because it can be self-hosted.

**Comment by guysoft** [comment]
Ok, so I got something like that to work here:
https://github.com/guysoft/CustomPiOS/blob/devel/.github/workflows/docker-build.yml

Had to do it because docker hub disabled their automated builds for free projects. So I have a feeling its a good path for here too.

**Comment by macropin** [comment]
Thanks for this. It's taken us a while to get around to reviewing this. We've implemented arm builds in d2668332d882566d1183839397b09f78d4b24153 using the GH `docker/build-push-action@v3`. PR #81 will add arm32 arch support.

**Pull request closed without merging**
